apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app-deployment
  namespace: Sandesh-ns
  labels:
    app: streamlit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      name: streamlit-app
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-app
          image: sandeshnavsare/streamlit-application:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
  namespace: Sandesh-ns
spec:
  type: NodePort
  selector:
    app: streamlit-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31100
